block production time
Cerebellum-Network/laboratory-api pull request #10
Opened 2021-03-12 13:40 UTC by karthikeyan-cere

service to return block production time

2021-03-15 06:07 UTC, evgeny-s requested changes

2021-03-15 06:07 UTC, evgeny-s commented on src/modules/health/health.controller.ts
> +  @Get('node-dropped')
This is the scope of the other ticket, right?

2021-03-15 06:07 UTC, evgeny-s commented on src/modules/health/health.service.ts
> +          // eslint-disable-next-line prefer-destructuring
Can we use destructuring instead of disabling of linter?

2021-03-15 06:09 UTC, karthikeyan-cere commented on src/modules/health/health.controller.ts
> +  @Get('node-dropped')
Yes.

2021-03-15 10:50 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +          // eslint-disable-next-line prefer-destructuring
Removed.

2021-03-15 12:31 UTC, evgeny-s commented on src/modules/health/health.controller.ts
> +  @Get('node-dropped')
ok, let's exclude these changes from this PR

2021-03-19 10:31 UTC, evgeny-s approved these changes

2021-03-19 10:31 UTC, merged