Features/different network
Cerebellum-Network/laboratory-api pull request #11
Opened 2021-03-16 11:22 UTC by karthikeyan-cere

Switch network for friendly bot.

2021-03-16 13:46 UTC, evgeny-s requested changes
Please check comments and don't forget to fix merge conflicts before submitting for review.

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/entities/payout.entity.ts
> +  TESTNET = '0',
Can we use the same name like: TESTNET='TESTNET'

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.interface.ts
> +  issueToken(destination: string, network:string): Promise<AssetDto>;
Let's use enum for the type here.

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +enum NETWORKS {
Why do we have duplication for Networks?
Remove from here, move the separate file

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +  private testNetApi: ApiPromise;
Let's do it in more flexible way:
```
private networks: { api: ApiPromise, keyRing: KeyringPair }[] = []; // custom object can be also moved to DTO
```

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +  public async testNetInit(): Promise<ApiPromise> {
Combine everything in 1 method.
The idea - we should be able to add new network, just by adding parameters to the ENV file

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +        break;
Throw error here about incorrect network parameter

2021-03-16 13:46 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +        break;
Throw error here about incorrect network parameter

2021-03-16 13:46 UTC, evgeny-s commented on .env.local
> +TESTNET_WS_URL=TESTNET_WS_URL
Can we convert it to array of objects?
```
NETWORK_PARAMS=[{url: '', wallet: '', passphrase: ''}]
```

2021-03-18 12:40 UTC, karthikeyan-cere commented on src/modules/friendly-bot/entities/payout.entity.ts
> +  TESTNET = '0',
Done.

2021-03-18 12:40 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.interface.ts
> +  issueToken(destination: string, network:string): Promise<AssetDto>;
Done.

2021-03-18 12:40 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +enum NETWORKS {
Done.

2021-03-18 12:40 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +  private testNetApi: ApiPromise;
Done.

2021-03-18 12:41 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +  public async testNetInit(): Promise<ApiPromise> {
Done.

2021-03-18 12:41 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +        break;
Done.

2021-03-18 12:41 UTC, karthikeyan-cere commented on .env.local
> +TESTNET_WS_URL=TESTNET_WS_URL
Done

2021-03-18 12:44 UTC, evgeny-s requested changes

2021-03-18 12:44 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +      case NetworkEnum.TESTNET: {
Can we remove this switch/case and get parameter form function argument?

2021-03-18 12:44 UTC, evgeny-s commented on .env.local
> +APP_WALLET_JSON=APP_WALLET_JSON
Let's put these parameters to the NETWORK, in case we want to change only for mainnet later. So we can configure them individually.

2021-03-18 12:44 UTC, evgeny-s commented on .env.local
> +APP_WALLET_JSON=APP_WALLET_JSON
And of course - remove these parameteres from here. So we have only NETWORKS with such kind of configuration

2021-03-18 12:44 UTC, evgeny-s commented on src/modules/friendly-bot/entities/payout.entity.ts
> +export enum NetworkEnum {
Let's remove this enum and use `string` type. In this case we can configure new networks only via ENV.

2021-03-18 12:44 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.interface.ts
> +  issueToken(destination: string, network:string): Promise<AssetDto>;
ignore this

2021-03-18 12:44 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
> +    const appWalletJson = this.configService.get('APP_WALLET_JSON');
Remove this from here and initialize N different assets, based on network config.

2021-03-18 12:44 UTC, evgeny-s commented on src/modules/friendly-bot/friendly-bot.service.ts
In this case we don't need this property here.

2021-03-18 13:17 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +      case NetworkEnum.TESTNET: {
done.

2021-03-18 13:17 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +      case NetworkEnum.TESTNET: {
done

2021-03-18 13:17 UTC, karthikeyan-cere commented on .env.local
> +APP_WALLET_JSON=APP_WALLET_JSON
done.

2021-03-18 13:37 UTC, karthikeyan-cere commented on src/modules/friendly-bot/entities/payout.entity.ts
> +export enum NetworkEnum {
done

2021-03-18 13:37 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
> +    const appWalletJson = this.configService.get('APP_WALLET_JSON');
done

2021-03-18 13:37 UTC, karthikeyan-cere commented on src/modules/friendly-bot/friendly-bot.service.ts
done

2021-03-18 15:00 UTC, evgeny-s approved these changes

2021-03-18 15:00 UTC, merged