Features/treasury balance
Cerebellum-Network/laboratory-api pull request #13
Opened 2021-03-23 12:03 UTC by karthikeyan-cere

Added treasury balance in peers module

2021-03-23 14:52 UTC, evgeny-s requested changes

2021-03-23 14:52 UTC, evgeny-s commented on src/main.ts
> +  // blockScannerService.init();
Shouldn't we revert it?

2021-03-23 14:52 UTC, evgeny-s commented on src/modules/peers/peer.controller.ts
> +    const balance = await this.peerService.treasuryBalance(network);
redundant variable:
* Change to `return this.pee....`
* Remove `async` from this function

2021-03-23 14:54 UTC, evgeny-s commented
@karthikeyan-cere , do not forget release notes

2021-03-23 15:00 UTC, karthikeyan-cere commented on src/main.ts
> +  // blockScannerService.init();
reverted it.

2021-03-23 15:00 UTC, karthikeyan-cere commented on src/modules/peers/peer.controller.ts
> +    const balance = await this.peerService.treasuryBalance(network);
updated.

2021-03-24 08:27 UTC, evgeny-s approved these changes

2021-03-24 12:28 UTC, merged