Added polygon module to track balance
Cerebellum-Network/laboratory-api pull request #53
Opened 2021-08-30 09:39 UTC by karthikeyan-cere

2021-08-30 21:23 UTC, AndreiNavoichyk requested changes
This is a typical task when you need the same functionality for different providers. Extract in interface the specific logic, prepare implementations for Substrate and EVM based Networks, integrate them into service.

2021-08-30 21:23 UTC, AndreiNavoichyk commented on src/modules/polygon/polygon.controller.ts
> +@Controller('polygon')
You don't need a separate controller. Use existing one `health`

2021-08-30 21:23 UTC, AndreiNavoichyk commented on src/modules/polygon/polygon.service.ts
> +  public logger = new Logger(PolygonService.name);
You don't need public logger.

2021-08-30 21:23 UTC, AndreiNavoichyk commented on src/modules/polygon/polygon.service.ts
> +  private inti() {
Check

2021-08-30 21:23 UTC, AndreiNavoichyk commented on src/modules/polygon/polygon.service.ts
> +  public provider: Map<string, {provider: Web3}> = new Map<string, {provider: Web3}>();
It can not be public. With this implementation, you lost control over data. It can be easily changed outside the class. Make it private and update the class API.

2021-08-30 21:23 UTC, AndreiNavoichyk commented on src/modules/polygon/polygon.service.ts
> +  public accounts: Map<string, {account: [AccountData]}> = new Map<string, {account: [AccountData]}>();
The same.

2021-08-31 07:04 UTC, karthikeyan-cere commented on src/modules/polygon/polygon.service.ts
> +  public logger = new Logger(PolygonService.name);
Updated to private

2021-09-01 06:42 UTC, karthikeyan-cere commented on src/modules/polygon/polygon.controller.ts
> +@Controller('polygon')
Removed

2021-09-03 09:54 UTC, AndreiNavoichyk requested changes

2021-09-03 09:54 UTC, AndreiNavoichyk commented on README.md
> +* Added support to monitor polygon account balance .
Fix extra space before `.`

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/health.controller.ts
> +// import {PolygonService} from './polygon.service';
Remove or uncomment

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/health.controller.ts
> +    } catch (error) {
Fix formatting here and everywhere.

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/health.controller.ts
> +    } catch (error) {
Fix formatting here and everywhere.

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +  private init(): void {
Move this logic to Networks classes.

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +    const cereBlockchain = new CereNetwork(this.cereNetwork, this.cereAccounts);
Initialization should be done via DI container.

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/polygon.service.ts
> +    if (!this.hasNetwork(network)) {
Stop copy-paste code. Move to a separate function and use it everywhere.

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/polygon.service.ts
> +export class PolygonNetwork implements IBlockchain {
Rename the file.

2021-09-03 09:54 UTC, AndreiNavoichyk commented on src/modules/health/cere.service.ts
> +export class CereNetwork implements IBlockchain {
Rename the file.

2021-09-03 10:03 UTC, karthikeyan-cere commented on src/modules/health/health.controller.ts
> +    } catch (error) {
Done

2021-09-03 10:03 UTC, karthikeyan-cere commented on src/modules/health/health.controller.ts
> +    } catch (error) {
Done

2021-09-03 10:03 UTC, karthikeyan-cere commented on src/modules/health/health.controller.ts
> +// import {PolygonService} from './polygon.service';
Removed

2021-09-03 10:03 UTC, karthikeyan-cere commented on README.md
> +* Added support to monitor polygon account balance .
Removed

2021-09-03 12:28 UTC, karthikeyan-cere commented on src/modules/health/cere.service.ts
> +export class CereNetwork implements IBlockchain {
renamed

2021-09-03 12:29 UTC, karthikeyan-cere commented on src/modules/health/polygon.service.ts
> +export class PolygonNetwork implements IBlockchain {
rename

2021-09-03 12:29 UTC, karthikeyan-cere commented on src/modules/health/polygon.service.ts
> +    if (!this.hasNetwork(network)) {
rename

2021-09-03 12:29 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +  private init(): void {
moved

2021-09-03 12:47 UTC, AndreiNavoichyk requested changes

2021-09-03 12:47 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +const cere = 'CERE';
Remove duplicate.

2021-09-03 12:47 UTC, AndreiNavoichyk commented on src/modules/health/polygon.network.ts
> +const polygon = 'POLYGON';
constant should be in 1 place.

2021-09-03 12:47 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +    api: Web3 | ApiPromise,
Why do you need `api` here? Implementation should know how to fetch the balance.

2021-09-03 14:05 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +    api: Web3 | ApiPromise,
Updated

2021-09-03 14:05 UTC, karthikeyan-cere commented on src/modules/health/polygon.network.ts
> +const polygon = 'POLYGON';
Updated

2021-09-03 14:05 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +const cere = 'CERE';
Removed

2021-09-06 07:44 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +export const BLOCKCHAIN_INTERFACE = 'BLOCKCHAIN_INTERFACE';
Do you use this somewhere?

2021-09-06 07:44 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +export type network = Map<string, {api: Web3 | ApiPromise}>;
Do you use this somewhere?

2021-09-06 07:44 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +    const blockchainService = this.getBlockchainInstance(cere);
It's not a blockchain service. It is blockchain. Rename here and everywhere.

2021-09-06 07:51 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +export const BLOCKCHAIN_INTERFACE = 'BLOCKCHAIN_INTERFACE';
removed

2021-09-06 07:51 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +export type network = Map<string, {api: Web3 | ApiPromise}>;
removed

2021-09-06 07:55 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +    const blockchainService = this.getBlockchainInstance(cere);
Renamed.

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +  private blockchain: Map<string, IBlockchain> = new Map<string, IBlockchain>();
Name collections in the plural.

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/health.service.ts
> +    const blockchainNetwork: IBlockchain = this.getBlockchainInstance(blockchain);
Rename so it has single name in all methods. For instance, `currentBlockchain`.

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  healthCheck?(network: string): Promise<any>;
Rename the methods so they have a verb

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  blockStatus?(network: string): Promise<BlockStatusDto>;
Rename the methods so they have a verb

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  finalization?(network: string): Promise<boolean>;
Rename the methods so they have a verb

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  blockProduction?(network: string): Promise<boolean>;
Rename the methods so they have a verb

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  validatorSlashed?(): Promise<void>;
Rename the methods so they have a verb

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  nodeDropped?(network: string): Promise<any>;
Rename the methods so they have a verb

2021-09-06 08:30 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  nodeDroppedStatus?(network: string): Promise<any>;
Rename the methods so they have a verb

2021-09-06 08:38 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +  private blockchain: Map<string, IBlockchain> = new Map<string, IBlockchain>();
Done

2021-09-06 09:00 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +    const blockchainNetwork: IBlockchain = this.getBlockchainInstance(blockchain);
updated.

2021-09-06 09:00 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  healthCheck?(network: string): Promise<any>;
updated

2021-09-06 09:00 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  finalization?(network: string): Promise<boolean>;
updated

2021-09-06 09:00 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  validatorSlashed?(): Promise<void>;
updated

2021-09-06 09:00 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  nodeDropped?(network: string): Promise<any>;
updated

2021-09-06 09:00 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  nodeDroppedStatus?(network: string): Promise<any>;
updated

2021-09-06 09:22 UTC, AndreiNavoichyk commented on src/modules/health/cere.network.ts
> +export const cere = 'CERE';
Use SNAKE_UPPER_CASE for constants.

2021-09-06 09:22 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  getSlashedValidator?(): Promise<void>;
Should this method be in interface?

2021-09-06 09:22 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  getBlockProduction?(network: string): Promise<boolean>;
Please, rename. The method responsibility is not clear.

2021-09-06 09:22 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  getWallet(network: string, wallet: string);
Rename `wallet`. Why do you need a method if you already have wallet?

2021-09-06 09:22 UTC, AndreiNavoichyk commented on src/modules/health/polygon.network.ts
> +export const polygon = 'POLYGON';
Use SNAKE_UPPER_CASE for constants.

2021-09-06 09:42 UTC, karthikeyan-cere commented on src/modules/health/cere.network.ts
> +export const cere = 'CERE';
updated

2021-09-06 09:42 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  getSlashedValidator?(): Promise<void>;
removed

2021-09-06 09:42 UTC, karthikeyan-cere commented on src/modules/health/polygon.network.ts
> +export const polygon = 'POLYGON';
done

2021-09-06 09:43 UTC, karthikeyan-cere commented on src/modules/health/blockchain.interface.ts
> +  getWallet(network: string, wallet: string);
getWallet will return a specific wallet whereas getWallets will return all the wallets in a particular network.

2021-09-06 10:09 UTC, AndreiNavoichyk approved these changes

2021-09-06 10:09 UTC, AndreiNavoichyk commented on src/modules/health/blockchain.interface.ts
> +  getWallet(network: string, wallet: string);
I mean wallet parameter. It looks like you have a wallet, passing it as a parameter to the method and trying to get one more wallet? Rename to `walletAddress` or smth

2021-09-06 15:07 UTC, merged