adding health-check and block status
Cerebellum-Network/laboratory-api pull request #8
Opened 2021-03-05 09:06 UTC by karthikeyan-cere

Added support for a node health check and block status

2021-03-05 09:16 UTC, evgeny-s requested changes
Check comments

2021-03-05 09:16 UTC, evgeny-s commented on src/modules/block-scanner/block-scanner.controller.ts
> +  @Get('health-check')
Create a separate module - `health` and move this logic there.
It should have [this](https://www.notion.so/cere/Understand-why-finalization-hanged-and-add-alerts-for-diff-between-block-produced-and-finalized-019b68be7e0c43a3bcf5de826b923e59#8947c7a51d804195b617c39b24cda0fd) endpoint.

2021-03-05 09:16 UTC, evgeny-s commented on src/modules/block-scanner/block-scanner.controller.ts
> +    return this.blockScannerService.healthCheck();
It should return have 204 status code in case if everything is ok, or 404 if not. 
Please check ticket details

2021-03-05 09:16 UTC, evgeny-s commented on src/modules/block-scanner/block-scanner.controller.ts
> +  @Get('health-check')
In the future, we will want to extend this module

2021-03-05 09:16 UTC, evgeny-s commented on src/modules/block-scanner/block-scanner.service.ts
> +    if (best - finalized > 10) {
Move 10 to ENV file. It should be configurable

2021-03-05 13:28 UTC, karthikeyan-cere commented on src/modules/block-scanner/block-scanner.controller.ts
> +  @Get('health-check')
address the comment

2021-03-05 13:28 UTC, karthikeyan-cere commented on src/modules/block-scanner/block-scanner.controller.ts
> +    return this.blockScannerService.healthCheck();
done.

2021-03-05 13:31 UTC, evgeny-s requested changes

2021-03-05 13:31 UTC, evgeny-s commented on src/modules/health/health.controller.ts
> +    if (diff > 10) {
Move to the ENV file

2021-03-05 13:31 UTC, evgeny-s commented on src/modules/health/health.service.ts
> +    if (best - finalized > 10) {
Do we need this duplication check here?

2021-03-05 13:31 UTC, evgeny-s commented on src/modules/health/health.service.ts
> +    if (best - finalized > 10) {
Let's get rid of this check in controller, because this logic should not be in the controller.

2021-03-08 03:54 UTC, karthikeyan-cere commented on src/modules/block-scanner/block-scanner.service.ts
> +    if (best - finalized > 10) {
Done.

2021-03-08 03:54 UTC, karthikeyan-cere commented on src/modules/health/health.controller.ts
> +    if (diff > 10) {
Done

2021-03-08 03:54 UTC, karthikeyan-cere commented on src/modules/health/health.service.ts
> +    if (best - finalized > 10) {
Moved to service file

2021-03-10 12:25 UTC, evgeny-s approved these changes

2021-03-10 13:25 UTC, merged